lane :test do
  analyze_commits(match: 'v*')
  notes = conventional_changelog
  puts(notes)
end

lane :publish do
  is_releasable = analyze_commits(match: 'v*')

  next unless is_releasable

  next_version = lane_context[SharedValues::RELEASE_NEXT_VERSION]
  # generates release notes for this version
  notes = conventional_changelog(
    order: ["feat", "fix", "docs"]
  )

  # Put down the next version - it will be taken in gemspec then
  # see .gemspec and version.rb
  code = "module Fastlane module SemanticRelease VERSION = \"#{next_version}\" end end"
  filepath = "../lib/fastlane/plugin/semantic_release/version.rb"
  sh("echo '#{code}' > #{filepath}")

  filename = "fastlane-plugin-semantic_release-#{next_version}.gem"
  tag = "v#{next_version}"

  sh("rake build")
  sh("gem push ../pkg/#{filename}")

  add_git_tag(tag: tag)
  push_git_tags

  set_github_release(
    repository_name: "xotahal/fastlane-plugin-semantic_release",
    api_token: ENV["GITHUB_TOKEN"],
    name: next_version,
    tag_name: tag,
    description: notes,
    commitish: "master",
    upload_assets: ["./pkg/#{filename}"]
  )
end
