lane :test do
  analyze_commits(match: 'v*')
  notes = conventional_changelog
  puts(notes)
end

lane :publish do
  is_releasable = analyze_commits(match: 'v*')

  unless is_releasable
    UI.message('Nothing to release')
    next
  end

  next_version = lane_context[SharedValues::RELEASE_NEXT_VERSION]
  # generates release notes for this version
  notes = conventional_changelog(
    order: ["feat", "fix", "docs"]
  )

  # Put down the next version - it will be taken in gemspec then
  # see .gemspec and version.rb
  code = "module Fastlane module SemanticRelease VERSION = \"#{next_version}\" end end"
  filepath = "../lib/fastlane/plugin/semantic_release/version.rb"
  sh("echo '#{code}' > #{filepath}")

  filename = "fastlane-plugin-semantic_release-#{next_version}.gem"
  tag = "v#{next_version}"

  sh("rake build")
  sh("gem push ../pkg/#{filename}")

  add_git_tag(tag: tag)
  push_git_tags

  notes_file = "../RELEASE_NOTES.md"
  File.write(notes_file, notes)
  sh("gh release create #{tag} ./pkg/#{filename} --title '#{next_version}' --notes-file '#{notes_file}' --target master")
  File.delete(notes_file)
end
